### ISSUE TITLE
Incorrect behaviour on empty line

### ISSUE THREAD

**Issue by migotom** [rs/net-server-mail#13]
According to RFC5321 section 4.3.2 Command-Reply Sequences server should just reply with 500 for invalid command.

Current implementation reply with 500 and write perl error message.

Steps to reproduce issue:
1. Start service
2. Telnet to it
```
telnet localhost 2500
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

220 Server.com ESMTP Service ready

500 Syntax error: unrecognized command
```
3. Read error from console:
`Use of uninitialized value $verb in uc at /home/getresponse/perl/lib/site_perl/5.28.0/Net/Server/Mail.pm line 564.`

**Comment by andee** [comment]
Indeed. New line sent to server can cause this bug. Fix looks fine.

**Comment by guimard** [comment]
Thanks !

**Comment by bbkr** [comment]
Hi. Can you please make CPAN release with this fix?

Thanks!

**Comment by guimard** [comment]
Done, thanks for this report !
