### ISSUE TITLE
"quit" broken

### ISSUE THREAD

**Issue by bbkr** [rs/net-server-mail#15]
Bug was introduced in:

```$line =~ s/^(.*\s)/uc($1)/ge;```

Lowercased "quit" does not have any following params. Because of that `\s `does not match and command is not uppercased. Therefore it is not recognized as registered command:

```
< 220 Service ready
> quit 
< 500 Syntax error: unrecognized command
```

**Comment by guimard** [comment]
Fix included in release 0.28. Thanks for this report!
