### ISSUE TITLE
Test `lmtp.t` fails

### ISSUE THREAD

**Issue by xsawyerx** [rs/net-server-mail#8]
When running the testing suite, the `lmtp.t` test fails for me. CPAN Testers shows an issue on [Windows](http://www.cpantesters.org/cpan/report/0c90dea0-6bfc-1014-bb50-a2c78d116242), but I'm running GNU/Linux here, so I'm not sure why it's failing. I'm investigating further and hope to update with what I learn.

```
1..11
ok 1 - use Net::Server::Mail::LMTP;
ok 2
ok 3
ok 4
ok 5
ok 6
ok 7
ok 8
ok 9
ok 10
not ok 11
#   Failed test at t/lmtp.t line 52.
# Looks like you failed 1 test of 11.
```

**Comment by xsawyerx** [comment]
More information:

```
Net::LMTP: Unexpected EOF on command channel at /usr/share/perl/5.18/Net/Cmd.pm line 289.
        Net::Cmd::getline('Net::LMTP=GLOB(0x2617038)') called at /usr/share/perl/5.18/Net/Cmd.pm line 345
        Net::Cmd::response('Net::LMTP=GLOB(0x2617038)') called at /home/sawyer/perl5/lib/perl5/Net/LMTP.pm line 365
        Net::LMTP::_QUIT('Net::LMTP=GLOB(0x2617038)') called at /home/sawyer/perl5/lib/perl5/Net/LMTP.pm line 342
        Net::LMTP::quit('Net::LMTP=GLOB(0x2617038)') called at /usr/share/perl/5.18/Net/Cmd.pm line 289.
        Net::Cmd::getline('Net::LMTP=GLOB(0x2617038)') called at /usr/share/perl/5.18/Net/Cmd.pm line 345
        Net::Cmd::response('Net::LMTP=GLOB(0x2617038)') called at /home/sawyer/perl5/lib/perl5/Net/LMTP.pm line 365
        Net::LMTP::_QUIT('Net::LMTP=GLOB(0x2617038)') called at /home/sawyer/perl5/lib/perl5/Net/LMTP.pm line 342
        Net::LMTP::quit('Net::LMTP=GLOB(0x2617038)') called at t/lmtp.t line 56
```

**Comment by xsawyerx** [comment]
I *think* the problem stems from calling `dataend` on the [Net::Cmd](https://metacpan.org/pod/Net::Cmd) object and *then* calling `response` on it. The documentation for my version[1] indicates that `dataend` will call `response` already, which means the test calls `response` twice (once implicitly by calling `dataend` and once explicitly a line after). This is possibly why it's getting a timeout the second time. the first time returns true.

If the explicit call to `response` is removed, the test passes. The following `quit` starts returning true too, once the following `response` is removed, which it did not before. That supports the notion that it should be removed.

What I'm not sure is why it doesn't fail in tests on CPAN Testers. My guess was that the test simply wasn't run, due to it being *optional*, depending on whether [Net::LMTP](https://metacpan.org/pod/Net::LMTP) is available or not.

[1]

    dataend ()
        End the sending of data to the remote server. This is done by ensuring that the data already sent ends with CRLF then sending '.CRLF'
        to end the transmission. Once this data has been sent "dataend" calls "response" and returns true if "response" returns CMD_OK.

**Comment by xsawyerx** [comment]
Given #10 is merged, this ticket can now be closed.

**Comment by guimard** [comment]
Hi, thanks for your contribution, can you review my last changes and confirm them for 0.23 ?
Regards,
Xavier

**Comment by xsawyerx** [comment]
Looks good to me.

Thank you. :)
